---
- hosts: application
  vars:
    node_version : 14
  tasks:

    #Instalar as chaves GPG
    - name: Instalar as chaves GPG do NodeJS
      apt_key: 
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
      become: yes

    #Instalar os repositorios
    - name: Instalar os repositórios do NodeJS
      apt_repository: 
        repo: "deb https://deb.nodesource.com/node_{{node_version}}.x {{ ansible_facts.distribution_release }} main"
        state: present
        update_cache: yes
      become: yes

    #Instalar o NodeJS
    - name: Instalar o NodeJS {{ node_version }}
      apt:
        name: nodejs
        state: latest
      become: yes


    ##Aplicação
    
    #Clonar repositorio
    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/busycore/nodexapp.git'
        dest: /vagrant/nodex
      register: git_download

    ##Copiar arquivos de uma pasta para outra
    - name: Copiar arquivos
      copy:
        src: /vagrant/nodex/
        dest: /vagrant/app/
      when: git_download.changed


    #Baixar Yarn usando npm
    - name: Instalar Yarn via npm
      community.general.npm:
        name: yarn
        global: yes
      become: yes

  #Baixar dependencias usando yarn
    - name: Instalar baseado no package.json.
      community.general.yarn:
        path: /vagrant/app

    - name : Atualizar as configurações
      replace:
        path: /vagrant/app/index.js
        regexp: "{{ item.campo }}"
        replace: "{{ item.valor }}"
      with_items:
        - { campo: 'APP_DB_HOSTNAME',valor: '172.28.128.91' }
        - { campo: 'APP_DB_USERNAME',valor: 'joao' }
        - { campo: 'APP_DB_PASSWORD',valor: 123456 }
        - { campo: 'APP_DB_NAME',valor: 'produtos' }
      when: git_download.changed 